version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: placeholder
      POSTGRES_DB: any_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data: