version: '3.8'

services:
  # This service is your Go application acting as a PostgreSQL server
  psql_wire_server:
    build: .
    ports:
      - "5432:5432"
    environment:
      - LISTENING_PORT=${LISTENING_PORT}
      - EXPECTED_PASSWORD=${EXPECTED_PASSWORD}
      - EXPECTED_USER=${EXPECTED_USER}

  # This service runs a one-time test against your server
  psql_client_test:
    image: postgres:14-alpine
    depends_on:
      - psql_wire_server
    environment:
      - PGPASSWORD=placeholder
    # This command waits 5 seconds for the server to initialize,
    # then attempts to connect and execute 'SELECT 1'.
    command: >
      sh -c "
        sleep 5 &&
        psql -h host.docker.internal -U sample -d any_db -c 'SELECT 1;'
      "
    restart: "no"